<html>
    <head>
        <title>Восстановление пароля</title>
    </head>
    <body>
        <h1>Восстановление пароля</h1>
        <p>
            Здравствуйте, <a href="<?php echo $this->serverUrl().$this->url(array('action' => 'view', 'username' => $this->user->username),
                'default', true)?>"><?php echo $this->escape($this->profile->fullname ? $this->profile->fullname : $this->user->username)?></a>!
        </p>
        <p>
            Вы запросили новый пароль для своей учётной записи, если вы этого не делали
            или передумали менять свой пароль, просто проигнорируйте это письмо.
        </p>
        <p>
            Для восстановления пароля перейдите по
            <a href="<?php echo $this->serverUrl().$this->url(array('action' => 'restore', 'controller' => 'auth', 'token' => $this->token))?>">этой ссылке</a></p>
        <p>Если вы не можете перейти по ссылке, то скопируйте ее и встате в браузер:<br />
            <?php echo $this->serverUrl().$this->url(array('action' => 'restore', 'controller' => 'auth', 'token' => $this->token))?>
        </p>
    </body>
</html>