<?= $this->doctype(); ?>
<html lang="ru">
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle() ?>
        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="header">
            <?= $this->render('partial/header.phtml') ?>
            <?= $this->render('partial/menu_line.phtml') ?>
        </div>
        
        <div class="content">
            <?= $this->layout()->content; ?>
            
            <?= $this->render('partial/narrow.phtml')?>
            
            <div class="cb"></div>
        </div>
        
        <?= $this->render('partial/categories.phtml') ?>
        
        <div class="footer">
            <?= $this->render('partial/footer.phtml') ?>
        </div>
        
        <?= $this->inlineScript(); ?>
    </body>
</html>
