<?php echo $this->doctype(); ?>
<html lang="ru">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <?php echo $this->render('header.phtml'); ?>
        
        <div class="content">
            <?php echo $this->layout()->content; ?>
            <div class="cb"></div>
        </div>
        
        <?php echo $this->render('footer.phtml'); ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
