Восстановление пароля.

Здравствуйте, <?php echo $this->escape($this->profile->fullname ? $this->profile->fullname : $this->user->username)?>!
                
Вы запросили новый пароль для своей учётной записи, если вы этого не делали или передумали менять свой пароль, просто проигнорируйте это письмо.
            
Для восстановления пароля перейдите по ссылке <?php echo $this->serverUrl().$this->url(array('action' => 'restore', 'controller' => 'auth', 'token' => $this->token))?>
Если вы не можете перейти по ссылке, то скопируйте ее и встате в браузер.
