<div class="footer1">
    <div class="footer_inner">
        <a href="#" class="close"></a>
        <center style="font-size:11px;">Развернуть категории услуг</center><br/>
        <ul class="fl">
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
        </ul>
        <ul class="fl">
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
        </ul>
        <ul class="fl">
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
        </ul>
        <ul class="fl">
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
            <li><a href="#">Архетиктура</a></li>
        </ul>
        <div class="cb"></div>
    </div>
</div>