<div class="menu">
    <ul>
        <li><a href="#">Исполнителям</a></li>
        <li><a href="#">Работодателям</a></li>
        <li><a href="#">Сообщества</a></li>
        <li><a href="/about/project">О проекте</a></li>
    </ul>
    
    <a href="/project/add" class="add_proj"><img src="/images/add_proj_button.png" alt=""/></a>
    
    <form class="search fr">
        <input type="text" class="search fl" placeholder="Например, дизайн интерьера" name="s"/>
        <input type="submit" class="submit fl"/>
    </form>
</div>